# Generated by Django 3.0.7 on 2021-03-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viewed_tutorial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
