# Generated by Django 3.0.7 on 2021-03-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_app', '0002_user_viewed_tutorial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
