# Generated by Django 3.0.7 on 2021-03-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_app', '0003_auto_20210328_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group_id',
            new_name='group',
        ),
    ]
